server:
  port: 1234
  address: localhost

spring:
  application:
    name: kianchart

  datasource:
    url: jdbc:postgresql://localhost:5432/kian_test
    username: cloud
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:migrations/changelog-master.xml
    default-schema: public

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /v3/api-docs


