-- liquibase formatted sql

-- changeset amir:1743665034524-6
CREATE TABLE userEntities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(128)                            NOT NULL,
    fullname      VARCHAR(128)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    date_of_birth date                                    NOT NULL,
    gender        VARCHAR(255)                            NOT NULL,
    uuid          UUID,
    is_active     BOOLEAN                                 NOT NULL,
    is_delete     BOOLEAN                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset amir:1743665034524-2
CREATE TABLE permissionEntities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(128)                            NOT NULL,
    slug        VARCHAR(128)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    is_delete   BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

-- changeset amir:1743665034524-4
CREATE TABLE roleEntities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(128)                            NOT NULL,
    slug        VARCHAR(128)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    is_delete   BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

-- changeset amir:1743665034524-3
CREATE TABLE role_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id       BIGINT                                  NOT NULL,
    permission_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (id)
);


-- changeset amir:1743665034524-5
CREATE TABLE user_role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    role_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id)
);

-- changeset amir:1743665034524-1
CREATE TABLE files
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id BIGINT                                  NOT NULL,
    file       VARCHAR(256)                            NOT NULL,
    size       INTEGER                                 NOT NULL,
    type       VARCHAR(16)                             NOT NULL,
    extension  VARCHAR(32)                             NOT NULL,
    is_delete  BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_files PRIMARY KEY (id)
);

-- changeset amir:1743665034524-7
ALTER TABLE permissionEntities
    ADD CONSTRAINT uc_permissions_slug UNIQUE (slug);

-- changeset amir:1743665034524-8
ALTER TABLE roleEntities
    ADD CONSTRAINT uc_roles_slug UNIQUE (slug);

-- changeset amir:1743665034524-9
ALTER TABLE userEntities
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset amir:1743665034524-10
ALTER TABLE files
    ADD CONSTRAINT FK_FILES_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES userEntities (id);

-- changeset amir:1743665034524-11
ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissionEntities (id);

-- changeset amir:1743665034524-12
ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roleEntities (id);

-- changeset amir:1743665034524-13
ALTER TABLE user_role
    ADD CONSTRAINT FK_USER_ROLE_ON_ROLE FOREIGN KEY (role_id) REFERENCES roleEntities (id);

-- changeset amir:1743665034524-14
ALTER TABLE user_role
    ADD CONSTRAINT FK_USER_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES userEntities (id);

